matrix:
  include:
  - language: python
    name: 'pytest'
    python:
    - '3.7'
    install:
    - pip install -r requirements.txt
    - pip install codecov
    - pip install pytest
    - pip install pytest-cov
    script:
    - pytest
    after_success:
    - codecov
  - language: python
    name: 'flake8'
    python:
    - '3.7'
    install:
    - pip install -r requirements.txt
    - pip install flake8
    script:
    - flake8 paperminer
  - language: python
    name: 'mypy'
    python:
    - '3.7'
    install:
    - pip install -r requirements.txt
    - pip install mypy
    script:
    - mypy paperminer
